LLNL/shroud

- docs/pypreviouswork.rst
- docs/types.rst
- regression/forward.yaml
- regression/reference/forward/forward.json
- regression/reference/forward/forward.log
- regression/reference/forward/forward_types.yaml
- regression/reference/forward/luaforwardmodule.cpp
- regression/reference/forward/luaforwardmodule.hpp
- regression/reference/forward/output
- regression/reference/forward/pyClass3type.cpp
- regression/reference/forward/pyforwardhelper.cpp
- regression/reference/forward/pyforwardmodule.cpp
- regression/reference/forward/pyforwardmodule.hpp
- regression/reference/forward/typesforward.h
- regression/reference/forward/wrapClass2.cpp
- regression/reference/forward/wrapClass2.h
- regression/reference/forward/wrapfforward.f
- shroud/ast.py
- shroud/typemap.py
Looks like it was introduced when tabs were removed from the scope.
The tabs were accidentially causing create_class_typemap to always
create a typemap, like it should. Now explicitly, always create
typemap.  scope::\tname != scope::name
> Fix a problem with forward declarations

- regression/reference/example/example.json
- regression/reference/forward/forward.json
- regression/reference/include/include.json
- regression/reference/names/names.json
- regression/reference/none/none.json
- regression/reference/ownership/ownership.json
- regression/reference/pointers/pointers.json
- regression/reference/preprocess/preprocess.json
- regression/reference/scope/scope.json
- regression/reference/strings/strings.json
- regression/reference/templates/templates.json
- regression/reference/tutorial/tutorial.json
- regression/reference/types/types.json
- regression/reference/vectors/vectors.json
- shroud/ast.py
- shroud/typemap.py
- shroud/wrapc.py
- shroud/wrapp.py
It is only renamed internally. YAML still sets it as c++.
This change is to make it easier to use langage when
generating variable names.
dict(c++=[])  bad
dict(cxx=[])  good
> Rename language attribute from c++ to cxx

- regression/reference/example/example.json
- regression/reference/names/names.json
- regression/reference/templates/pyImplWorker1type.cpp
- regression/reference/templates/templates.json
- regression/reference/templates/templates_types.yaml
- regression/reference/templates/wraptemplates.cpp
- regression/reference/tutorial/tutorial.json
- regression/run/templates/implworker1.hpp
- regression/run/templates/templates.hpp
- regression/templates.yaml
- shroud/ast.py
- shroud/generate.py
- shroud/todict.py
- shroud/util.py
- shroud/wrapc.py
A cxx_header defined for a class must be added to the
implementation file -- see template.yaml.
Added variable gen_headers_typedef to keep track of types
used with template instantiation.
> Use cxx_header with template instantiation

- regression/forward.yaml
- regression/reference/forward/forward.json
- regression/reference/forward/forward_types.yaml
- regression/reference/forward/pyClass3type.cpp
- regression/reference/forward/wrapClass2.cpp
- shroud/util.py
- shroud/wrapc.py
It was putting both includes on the same line:
#include "header1.h header2.h"
Should be
#include "header1.h"
#include "header2.h"
> Allow impl_header to be a blank delimited list

- regression/reference/clibrary/wrapClibrary.h
- regression/reference/generic/wrapgeneric.h
- regression/reference/struct-c/wrapstruct.h
- regression/run/clibrary/python/test.py
- shroud/util.py
The generated headers are for use from C, and the implementation is
also compiled with C.
> Do not use c++ headers when language=c

- regression/reference/clibrary/wrapClibrary.h
- shroud/wrapc.py
Only include headers if the wrapper is written.
Fortran can call some functions without a wrapper.
> Remove excess includes from header

- docs/reference.rst
- regression/do-test.py
- regression/reference/classes/typesclasses.h
- regression/reference/memdoc/typesmemdoc.h
- regression/reference/memdoc/wrapfmemdoc.f
- regression/reference/memdoc/wrapmemdoc.cpp
- regression/reference/none/helpers.c
- regression/reference/none/helpers.f
- regression/reference/strings/typesstrings.h
- regression/reference/strings/wrapfstrings.f
- regression/reference/strings/wrapstrings.cpp
- regression/reference/tutorial/typesTutorial.h
- regression/reference/tutorial/wrapTutorial.cpp
- regression/reference/tutorial/wrapftutorial.f
- regression/reference/vectors/typesvectors.h
- regression/reference/vectors/wrapfvectors.f
- regression/reference/vectors/wrapvectors.cpp
- shroud/generate.py
- shroud/main.py
- shroud/util.py
- shroud/whelpers.py
- shroud/wrapc.py
- shroud/wrapf.py
- shroud/wrapp.py
* Create all helpers before creating wrappers. Before they were created on a as-needed basis as a sort of optimization.  However, the savings are minimal and added complication to wrappers.  Some helpers are created internally for each native type, many of which will never be used. However, they are still only added to the wrappers on a as-needed basis.  The final wrappers are the same after this change.
* Added --write-helpers option used to test helpers.
* Fixed some naming problems in wrappers by using flat_name instead of c_type.  For example the helper functions should be named using "long_long" and not "long long".
> Dump helpers

- regression/reference/example/example.json
- regression/reference/example/pyUserLibrary_example_nestedmodule.cpp
- regression/reference/ownership/ownership.json
- regression/reference/ownership/pyownershipmodule.cpp
- regression/reference/pointers-list-c/pointers.json
- regression/reference/pointers-list-c/pypointersmodule.c
- regression/reference/pointers-list-cxx/pointers.json
- regression/reference/pointers-list-cxx/pypointersmodule.cpp
- regression/reference/pointers-numpy-c/pointers.json
- regression/reference/pointers-numpy-c/pypointersmodule.c
- regression/reference/pointers-numpy-cxx/pointers.json
- regression/reference/pointers-numpy-cxx/pypointersmodule.cpp
- regression/reference/references/pyArrayWrappertype.cpp
- regression/reference/references/references.json
- regression/reference/templates/pystd_vector_doubletype.cpp
- regression/reference/templates/pystd_vector_inttype.cpp
- regression/reference/templates/templates.json
- shroud/wrapp.py
* Was: ["py", sgroup, intent, "dimension", options.PY_array_arg]
* Now: ["py", sgroup, spointer, intent, deref, options.PY_array_arg]
Adds spointer (`*`, `**`, `[]`) and deref (*pointer*, *allocatable*, *raw*)
This will put it on par with wrapf.py and make it easer to add py_statements for other cases.
> Use spointers in pystatements

- shroud/wrapp.py
wrapp.py was trying to use stmts_comments when it was undefined.
> Allow tests to run with debug=False

- shroud/generate.py
- tests/test_generate.py
It must have a value i.e. +dimension is an error.  Before this implied
assumed-size.  Files should now use +rank(1) to define assumed-shape.
> Add test on dimension attribute

- Makefile
- regression/do-test.py
- regression/input/enum.yaml
- regression/reference/enum-c/pyenummodule.c
- regression/reference/enum-c/pyenummodule.h
- regression/reference/enum-cxx/pyenummodule.cpp
- regression/reference/enum-cxx/pyenummodule.hpp
- regression/reference/example/pyUserLibrary_example_nestedmodule.cpp
- regression/reference/example/pyUserLibrary_examplemodule.cpp
- regression/reference/names/pytestnames_internalmodule.cpp
- regression/reference/names/pytestnames_ns0_innermodule.cpp
- regression/reference/names/pytestnames_ns0module.cpp
- regression/reference/names/pytestnames_ns1module.cpp
- regression/reference/names/pytestnames_stdmodule.cpp
- regression/reference/namespace/pyns_nsworkmodule.cpp
- regression/reference/namespace/pyns_outermodule.cpp
- regression/reference/namespacedoc/pywrapped_inner1module.cpp
- regression/reference/namespacedoc/pywrapped_inner2module.cpp
- regression/reference/namespacedoc/pywrapped_inner4module.cpp
- regression/reference/templates/pytemplates_internalmodule.cpp
- regression/reference/templates/pytemplates_stdmodule.cpp
- regression/run/enum-c/python/Makefile
- regression/run/enum-c/python/test.py
- regression/run/templates/python/test.py
- shroud/wrapp.py
* Rename enum module to cenum to avoid conflict with builtin enum
* Fixes for nested modules.  Also fixes Python 2 submodules.
* Remove DeprecationWarnings
> Python 3 fixes

- shroud/ast.py
Used when some options moved into format to help convert YAML files.
> Remove an old DeprecationWarning

- HACKING
- shroud/util.py
What's new Python 3.9:
When Python 2.7 was still supported, many functions were kept for
backward compatibility with Python 2.7. With the end of Python 2.7
support, these backward compatibility layers have been removed, or
will be removed soon. Most of them emitted a DeprecationWarning
warning for several years. For example, using collections.Mapping
instead of collections.abc.Mapping emits a DeprecationWarning since
Python 3.3, released in 2012.
> Fix DeprecationWarnings

- CHANGELOG.md
- docs/struct.rst
- regression/input/struct.yaml
- shroud/declast.py
Useful for opaque structs.
This also makes it possible to define members via the declarations
field in the YAML file. That's useful when options or format fields
need to be set on individual members.
> Allow struct to be define without members

- docs/cstatements.rst
- docs/typemaps.rst
- shroud/statements.py
- shroud/util.py
- shroud/wrapc.py
- shroud/wrapp.py
c_header and cxx_header replaced by c_impl_header and cxx_impl_header
and assigned to impl_header based on language by
update_for_language. Used in implementation.
impl_header will be added to C header file.
Useful for creating function prototypes.
> Add CStmts.iface_header and impl_header

- shroud/statements.py
- shroud/wrapl.py
- shroud/wrapp.py
The classes CStmts and FStmts were not being used consistently.  Works
better as a util.Scope since that's what they were being converted
into anyways in add_statement_to_tree.
> Convert CStmts, FStmts into util.Scope

- CHANGELOG.md
- shroud/main.py
Currently, we do a hard coded check for yaml in main.py, but it is often the case that the user might use yml. This small change allows for using either by using re.search on the extension pattern instead of a hard `==`. This will fix #221.
The way I ran into this bug was having a whole ton of options, etc., in my yml file, and absolutely nothing was seeming to work (e.g., I was generating .f for fortran when I expected python). I'm wondering how it knew to do anything if it couldn't read my yaml *.yml" file. I hope this helps a future user!
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
> allowing for yaml extension to be yml or yaml

- regression/input/names.yaml
- regression/reference/names/foo.cpp
- regression/reference/names/wraptestnames_ns0_inner.cc
- shroud/ast.py
It also cleans up empty lines. They are convert by libyaml to None and
must be changed to ''.
#243
> Allow YAML multiline text in splicer_code

- tests/test_declast.py
Constructors now return a pointer to the capsule.
> Update Python unit tests

- regression/reference/clibrary/clibrary.json
- regression/reference/cxxlibrary/cxxlibrary.json
- regression/reference/forward/forward.json
- regression/reference/forward/wrapfforward.f
- regression/reference/namespace/namespace.json
- regression/reference/scope/scope.json
- regression/reference/struct-c/struct.json
- regression/reference/struct-class-c/struct.json
- regression/reference/struct-class-cxx/struct.json
- regression/reference/struct-cxx/struct.json
- regression/reference/struct-list-cxx/struct.json
- regression/reference/struct-numpy-c/struct.json
- regression/reference/struct-numpy-cxx/struct.json
- regression/reference/struct-py-c/struct-py.json
- regression/reference/struct-py-cxx/struct-py.json
- regression/reference/structlist/structlist.json
- regression/reference/typedefs-c/typedefs.json
- regression/reference/typedefs-c/wrapftypedefs.f
- regression/reference/typedefs-cxx/typedefs.json
- regression/reference/typedefs-cxx/wrapftypedefs.f
- shroud/ast.py
- shroud/typemap.py
If the Typemap field is set via the fields dictionary, then do not compute a default value. Typically only f_derived_type is explicitly set. Then f_class, f_type, f_c_type, f_module and f_c_module are computed.  This is for class and struct Typemaps.
Set default argument value for fields to {} instead of None to allow it to always be treated as a dictionary (IN and UPDATE operations)
> Control when to set default Typedefs fields

- regression/reference/names/names.log
- regression/reference/templates/templates.log
- shroud/wrapc.py
- shroud/wrapf.py
Instead of listing some classes the same multiple time, now include the template arguments.
names.log Before
```
class vector
class vector
```
Now
```
class vector<int>
class vector<double>
```
> Print class instantiation in log

- regression/input/templates.yaml
- regression/reference/names/names.json
- regression/reference/templates/templates.json
- shroud/ast.py
- shroud/generate.py
Removes duplicate code in `GenFunctions.instantiate_classes` in `generate.py`.  Fixed issues in `default_format` to allow it to work with instantiations.
> Use ClassNode.default_format with class instantiation

- regression/run/Makefile
- regression/run/typemap64/Makefile
Needed when LOGOUTPUT is saved. Otherwise, test logs for c will be overwritten by the fortran log. Was build.out, now build-c.out and build-f.out.
Add -lm flag to typemap64 test which uses the pow functions.
> Write each language log to a new file

- docs/statements.rst
- regression/input/error-stmt.yaml
- regression/reference/error-stmt/output
- regression/reference/none/statements
- shroud/fc-statements.json
- shroud/statements.py
- shroud/wrapl.py
- shroud/wrapp.py
* Make the *name* field optional if *alias* is provided. This makes it possible to format all names/alias together to look
for possible errors by noticing patterns.
* Removes several intents (defaulttmp, shared) that were added for the same reason (to group all names together)
* Remove the permutation option in names ( f_in/out ) This made it harder to find names in `fc-statements.json` with grep/search. I had been adding comments in Python for all the expanded permutations, but JSON does not support comments.
> Allow name and alias to be merged in statements

- docs/releases.rst
- regression/reference/none/statements
- shroud/ast.py
- shroud/fc-statements.json
- shroud/statements.py
- shroud/typemap.py
Remove the old default value of `{cxx_var}` and explicitly set in `fc-statements.py`.
This removes it from function, ctor and mixin statement groups which do not need it.
> Explicitly set stmt.c_arg_call

- docs/cstatements.rst
- docs/fstatements.rst
- regression/input/sgroup.yaml
- regression/reference/none/statements
- regression/reference/pointers-c-f/wrapfpointers.f
- regression/reference/pointers-c/wrapfpointers.f
- regression/reference/pointers-cfi/wrapfpointers.f
- regression/reference/pointers-cxx-f/wrapfpointers.f
- regression/reference/pointers-cxx/wrapfpointers.f
- shroud/fc-statements.json
Use more mixin in ``fc-statements.json``
Factor out common functionality by using mixin groups.The format dictionary is now more complete so the same mixin can be used in more cases. native and char and void.
It should be easier to reason about what a group is doing and only the exception behavior is listed explicitly in the non-mixin groups. A lot more can be done in this direction.
> Refactor fc-statements

- regression/reference/cxxlibrary/pycxxlibrary_structnsmodule.cpp
- regression/reference/none/statements
- regression/reference/struct-numpy-c/pystructmodule.c
- regression/reference/struct-numpy-cxx/pystructmodule.cpp
- regression/reference/struct-py-c/pystructmodule.c
- regression/reference/struct-py-cxx/pystructmodule.cpp
- shroud/wrapp.py
Before, some shared code was added by assigning variables in `py_statements`
Old:
post_parse=[
] + array_error
New:
mixin=[
"py_mixin_array-FromAny",
"py_mixin_array_error",
]
This will make it possible to convert py-statements into JSON.
> Add mixin groups to wrapp.py

- regression/reference/none/statements
- shroud/statements.py
This changes the output with the `--write-statements` option so that `c_pre_cal`l defines a variable then `c_arg_call` uses it. Fortran already does this.
> Swap order of c_arg_call and c_pre_call

- regression/reference/none/statements
- shroud/fc-statements.json
Group together by use (native, char, string) and group their mixins togehter.  Create comments to label mixin sections.
This should make it easier for users to find a group with functionality.  It will also make it easier to identify groups which are similar and may be consolidated.
> Reorder some mixin groups

- regression/reference/char-cxx-cfi/char.json
- regression/reference/char-cxx/char.json
- regression/reference/char-cxx/wrapchar.cpp
- regression/reference/clibrary/clibrary.json
- regression/reference/funptr-c/funptr.json
- regression/reference/funptr-cxx/funptr.json
- regression/reference/names/names.json
- regression/reference/none/def_types.yaml
- regression/reference/none/none.json
- regression/reference/none/statements
- regression/reference/pointers-c-f/pointers.json
- regression/reference/pointers-c/pointers.json
- regression/reference/pointers-cfi/pointers.json
- regression/reference/pointers-cxx-c/pointers.json
- regression/reference/pointers-cxx-f/pointers.json
- regression/reference/pointers-cxx/pointers.json
- regression/reference/strings-cfi/strings.json
- regression/reference/strings/strings.json
- regression/reference/struct-c/struct.json
- regression/reference/struct-cxx/struct.json
- shroud/fc-statements.json
- shroud/typemap.py
Set to `SH_TYPE_CHAR`. It was defaulting to `SH_TYPE_OTHER`.
> define sh_type for Typemap char

- regression/reference/none/statements
- shroud/fc-statements.json
- shroud/statements.py
Make it easier to find and understand groups and fields by keeping similar groups together and fields in a consistent order.
> Reorder groups in fc-statements.json

- Makefile
- setup.py
- shroud/error.py
- shroud/main.py
- shroud/metaattrs.py
- shroud/statements.py
- shroud/util.py
- shroud/whelpers.py
The current limit on the PyYAML version does not work with newer versions of Python. setup.py provides syntax to specify dependencies based on python_version.
Also make a fix for Python 3.10 for collections.abc.Mapping.
Tested Python 2.7. It has rotted some and is not working. Added a few fixes.
Found a recursive import: statements - whelpers - statements Added a kludge by passing in statements module to the function in whelpers that needed it.
Import fc-statements.py with pyYAML instead of json to avoid unicode issues.
#392
> Update PyYAML dependency for Python 3

- regression/reference/none/statements
- regression/reference/vectors/wrapvectors.cpp
- shroud/fc-statements.json
Work to move some behavior to a single group and use via mixins.
> Refactor fc-statements.yaml groups 
