LLNL/shroud

- docs/reference.rst
- regression/reference/enum-c/enum.json
- regression/reference/enum-c/wrapenum.h
- regression/reference/enum-cxx/enum.json
- regression/reference/enum-cxx/wrapenum.h
- regression/reference/names/names.json
- regression/reference/namespace/namespace.json
- regression/reference/scope/scope.json
- regression/reference/tutorial/tutorial.json
- regression/run/enum-c/testc.c
- shroud/ast.py
- shroud/todict.py
- shroud/wrapc.py
- shroud/wrapf.py
Convert enum expression identifiers to the wrapper's names.
> Enum testc

- regression/reference/clibrary/clibrary.json
- regression/reference/example/example.json
- regression/reference/memdoc/memdoc.json
- regression/reference/names/names.json
- regression/reference/namespace/namespace.json
- regression/reference/strings/strings.json
- regression/reference/struct-c/struct.json
- regression/reference/struct-cxx/struct.json
- regression/reference/tutorial/tutorial.json
- regression/reference/vectors/vectors.json
- shroud/ast.py
- shroud/generate.py
- shroud/typemap.py
- shroud/wrapc.py
- shroud/wrapf.py
- shroud/wrapp.py
- tests/__init__.py
- tests/test_typemap.py
> Lookup stmts

- regression/reference/clibrary/wrapfclibrary.f
- regression/reference/example/wrapfUserLibrary_example_nested.f
- regression/reference/tutorial/wrapftutorial.f
- regression/reference/types/wrapftypes.f
- shroud/wrapf.py
The local variable created by c_local_var is moved from
arg_decl into declare.
> Move fstatements.c_local_var into splicer

- shroud/typemap.py
- shroud/util.py
- shroud/wrapc.py
- shroud/wrapp.py
Change Python wrapper to use Scope instances in py_tree converted from py_statements.
> Python typemap

- regression/run/clibrary/clibrary.c
- regression/run/clibrary/clibrary.h
- regression/run/clibrary/mainc.c
- regression/run/clibrary/python/testpython.c
- regression/run/enum-c/enum.h
- regression/run/enum-c/testc.c
- regression/run/forward/header1.hpp
- regression/run/forward/header2.hpp
- regression/run/forward/tutorial.hpp
- regression/run/forward/wrapClass1.h
- regression/run/generic/generic.c
- regression/run/generic/generic.h
- regression/run/generic/helper.c
- regression/run/generic/helper.h
- regression/run/namespace/testc.c
- regression/run/ownership/python/testpython.c
- regression/run/pointers/python/testpython.c
- regression/run/statement/statement.hpp
- regression/run/statement/testc.c
- regression/run/strings/python/testpython.c
- regression/run/struct-c/struct.c
- regression/run/templates/testc.c
- regression/run/tutorial/lua/testlua.c
- regression/run/tutorial/python/testpython.c
- regression/run/tutorial/testc.c
- regression/run/types/testc.c
> Remove excess includes from header

- regression/reference/classes/classes.json
- regression/reference/clibrary/clibrary.json
- regression/reference/example/example.json
- regression/reference/forward/forward.json
- regression/reference/generic/generic.json
- regression/reference/include/include.json
- regression/reference/names/names.json
- regression/reference/ownership/ownership.json
- regression/reference/pointers-list-c/pointers.json
- regression/reference/pointers-list-cpp/pointers.json
- regression/reference/pointers-numpy-c/pointers.json
- regression/reference/pointers-numpy-cpp/pointers.json
- regression/reference/strings/strings.json
- regression/reference/struct-c/struct.json
- regression/reference/struct-cxx/struct.json
- regression/reference/templates/templates.json
- regression/reference/tutorial/tutorial.json
- regression/reference/types/types.json
- regression/reference/vectors-list/vectors.json
- regression/reference/vectors-numpy/vectors.json
- regression/reference/vectors/vectors.json
- shroud/declast.py
- shroud/generate.py
- shroud/todict.py
- shroud/typemap.py
- shroud/wrapc.py
- shroud/wrapf.py
- shroud/wrapp.py
Use a defaultdict for attributes to simplify coding.
> Defaultdict

- shroud/typemap.py
- shroud/wrapc.py
- shroud/wrapf.py
- shroud/wrapp.py
- tests/test_typemap.py
Convert statements into list of dictionaries instead of dictionary of dictionaries.
> Statement with dict

- regression/reference/cdesc/typescdesc.h
- regression/reference/example/typesUserLibrary.h
- regression/reference/memdoc/typesmemdoc.h
- regression/reference/namespace/typesns.h
- regression/reference/strings/typesstrings.h
- regression/reference/tutorial/typesTutorial.h
- shroud/whelpers.py
Add defines for types when struct which holds the type is used.
> Add a dependency on ShroudTypeDefines

- docs/fortran.rst
- shroud/typemap.py
- shroud/wrapc.py
- shroud/wrapf.py
Remove unused members of Typemap: format and f_args.
> Cleanup typemap

- regression/input/struct.yaml
- regression/reference/struct-c/struct.json
- regression/reference/struct-c/wrapfstruct.f
- regression/reference/struct-class-c/pyCstruct_ptrtype.c
- regression/reference/struct-class-c/pystructmodule.h
- regression/reference/struct-class-c/pystructutil.c
- regression/reference/struct-class-c/struct.json
- regression/reference/struct-class-c/struct.log
- regression/reference/struct-class-cxx/pyCstruct_ptrtype.cpp
- regression/reference/struct-class-cxx/pystructmodule.hpp
- regression/reference/struct-class-cxx/pystructutil.cpp
- regression/reference/struct-class-cxx/struct.json
- regression/reference/struct-class-cxx/struct.log
- regression/reference/struct-cxx/struct.json
- regression/reference/struct-cxx/wrapfstruct.f
- regression/reference/struct-cxx/wrapstruct.h
- regression/reference/struct-list-cxx/pystructmodule.cpp
- regression/reference/struct-list-cxx/struct.json
- regression/reference/struct-numpy-c/pystructmodule.c
- regression/reference/struct-numpy-c/struct.json
- regression/reference/struct-numpy-cxx/pystructmodule.cpp
- regression/reference/struct-numpy-cxx/struct.json
- regression/reference/structlist/pystructutil.c
- regression/run/struct-class-c/python/test.py
- regression/run/struct-class-cxx/python/test.py
- regression/run/struct/struct.h
- shroud/generate.py
- shroud/whelpers.py
- shroud/wrapp.py
* Fix problem with missing numpy include files.
* Fix a case of pointer to scalar in struct  (double *member) without dimension attribute.
> Need numpy

- docs/typemaps.rst
- regression/reference/none/def_types.yaml
- regression/reference/none/none.json
- shroud/declast.py
- shroud/typemap.py
- shroud/wrapf.py
- tests/test_declast.py
Remove old code from Typemap which is now done in fc_statements.
> Cleanup typemaps

- docs/reference.rst
- regression/reference/none/helpers.f
- regression/reference/none/none.json
- regression/reference/ownership/wrapfownership.f
- regression/run/ownership/main.f
- shroud/ast.py
- shroud/whelpers.py
> Add type-bound funtion to delete capsule contents

- Makefile
- README.md
- dist-nuitka/shroud.py
Nuitka is a Python compiler written in Python.
> Distribution

- docs/cstatements.rst
- regression/reference/cdesc/cdesc.json
- regression/reference/cdesc/wrapcdesc.cpp
- regression/reference/cdesc/wrapfcdesc.f
- regression/reference/strings/strings.json
- regression/reference/strings/wrapfstrings.f
- shroud/statements.py
Add ability to have a fc_statement to be used by multiple values.
``c_native_*_in/out/inout_cfi`` expands into ``c_native_*_in_cfi``, ``c_native_*_out_cfi``, ``c_native_*_inout_cfi``
> Statements group

- docs/cstatements.rst
- regression/reference/none/statements
- shroud/generate.py
- shroud/statements.py
- shroud/typemap.py
It is now unused.
Should of been in last PR.
> Remove traces of buf_args

- regression/reference/clibrary/clibrary.json
- regression/reference/clibrary/clibrary_types.yaml
- regression/reference/cxxlibrary/cxxlibrary.json
- regression/reference/cxxlibrary/cxxlibrary_types.yaml
- regression/reference/namespace/namespace.json
- regression/reference/namespace/ns_types.yaml
- regression/reference/scope/scope.json
- regression/reference/scope/scope_types.yaml
- regression/reference/struct-c/struct.json
- regression/reference/struct-c/struct_types.yaml
- regression/reference/struct-class-c/struct.json
- regression/reference/struct-class-c/struct_types.yaml
- regression/reference/struct-class-cxx/struct.json
- regression/reference/struct-class-cxx/struct_types.yaml
- regression/reference/struct-cxx/struct.json
- regression/reference/struct-cxx/struct_types.yaml
- regression/reference/struct-list-cxx/struct.json
- regression/reference/struct-list-cxx/struct_types.yaml
- regression/reference/struct-numpy-c/struct.json
- regression/reference/struct-numpy-c/struct_types.yaml
- regression/reference/struct-numpy-cxx/struct.json
- regression/reference/struct-numpy-cxx/struct_types.yaml
- regression/reference/struct-py-c/struct-py.json
- regression/reference/struct-py-c/struct_types.yaml
- regression/reference/struct-py-cxx/struct-py.json
- regression/reference/struct-py-cxx/struct_types.yaml
- regression/reference/structlist/struct_types.yaml
- regression/reference/structlist/structlist.json
- shroud/ast.py
- shroud/typemap.py
Refactor to make it easier to understand and change in the future.
> Refactor creating struct and class typemaps

- regression/input/example.yaml
- regression/reference/clibrary/clibrary.json
- regression/reference/debugfalse/tutorial.json
- regression/reference/defaultarg/defaultarg.json
- regression/reference/example/example.json
- regression/reference/example/userlibrary_types.yaml
- regression/reference/include/include.json
- regression/reference/python-only/tutorial.json
- regression/reference/tutorial/tutorial.json
- shroud/ast.py
- shroud/todict.py
Record the user provided typemap fields so they may be reapplied if  needed.
> Set node.user_fields for TypedefNode and ClassNode

- regression/reference/error/output
- shroud/util.py
Include the name of the variable from the AttributeError.
> Improve error message in wformat

- regression/run/Makefile
- regression/run/sgroup/Makefile
- regression/run/sgroup/maincpp.cpp
- regression/run/sgroup/sgroup.cpp
- regression/run/sgroup/sgroup.hpp
- regression/run/templates/maincpp.cpp
- regression/run/templates/templates.hpp
- regression/run/tutorial/maincpp.cpp
- shroud/error.py
- tests/check_decl.output
- tests/test_declast.py
Cleanup from last pull request.
Eventually make sgroup.yaml a runable test.
> Move twostruct example to sgroup test

- .readthedocs.yml
- docs/classes.rst
- docs/fortran.rst
- docs/reference.rst
- docs/shared_ptr.rst
- regression/input/shared.yaml
- regression/reference/none/none.json
- regression/reference/shared/shared.json
- regression/reference/shared/shared.log
- regression/reference/shared/wrapObject_shared.cpp
- regression/reference/shared/wrapObject_shared.h
- regression/reference/shared/wrapfshared.f
- regression/run/shared/main.f
- regression/run/shared/maincpp.cpp
- shroud/ast.py
- shroud/generate.py
- shroud/wrapc.py
Add ability to control shared_ptr names
* option.C_name_shared_api_template
* format.C_name_shared_api
* format.F_name_shared_use_count
> Add use_count method on shared_ptr

- docs/appendix-A.rst
- docs/statements.rst
- regression/input/char.yaml
- regression/reference/char-cxx-cfi/wrapchar.cpp
- regression/reference/char-cxx-cfi/wrapfchar.f
- regression/reference/char-cxx/wrapchar.cpp
- regression/reference/char-cxx/wrapfchar.f
- regression/reference/none/statements
- shroud/fc-statements.json
- shroud/statements.py
The comments are created by accumulationg the mixin comments. Convert them to notes.
Update docs literalinclude for char-cxx.
> Do not use comments with non-mixin

- docs/cstatements.rst
- docs/input.rst
- regression/reference/none/statements
- shroud/statements.py
- shroud/wrapc.py
It must be set by the user via attribute or statement.
> Remove default for stmt.owner
